# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Blog"
 pageRef = "posts"
 weight = 10

[[main]]
 name = "KODI Addons"
 weight = 11

[[main]]
 name = "NPO"
 parent = "KODI Addons"
 pageRef = "kodi-npo/"
 weight = 12

[[main]]
 name = "RTLxl"
 parent = "KODI Addons"
 pageRef = "kodi-rtlxl/"
 weight = 13

[[main]]
 name = "Kanalenlijst Hans"
 parent = "KODI Addons"
 pageRef = "kodi-kanalenlijst-hans/"
 weight = 14

[[main]]
 name = "RISC-V"
 weight = 20

[[main]]
 name = "StarFive VisionFive 2"
 parent = "RISC-V"
 pageRef = "tags/starfive-visionfive-2"
 weight = 22

[[main]]
 name = "Milk-V Jupiter"
 parent = "RISC-V"
 pageRef = "tags/milk-v-jupiter"
 weight = 24

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

# [[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

# [[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
